### PR TITLE
Update Project.xml

### PR DESCRIPTION
**Pull request by BushTrain460615**

### CODE REVIEW

**Comment by BushTrain460615** [comment]
also I make Mac ports for my free time I made hxCodec work on Mac

**Comment by LeonGamerPS4** [comment]
Hmmm. It seems like buildMac failed to compile.

Undefined symbols for architecture x86_64:
  "_libvlc_audio_get_volume", referenced from:
      LibVLC::getVolume() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::getVolume() in 1686b029_VlcBitmap.o
  "_libvlc_audio_set_volume", referenced from:
      LibVLC::play(char const*) in 1686b029_VlcBitmap.o
      LibVLC::setVolume(float) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::play(String) in 1686b029_VlcBitmap.o
  "_libvlc_errmsg", referenced from:
      LibVLC::getLastError() in 1686b029_VlcBitmap.o
  "_libvlc_event_attach", referenced from:
      LibVLC::registerEvents() in 1686b029_VlcBitmap.o
  "_libvlc_event_detach", referenced from:
      LibVLC::~LibVLC() in 1686b029_VlcBitmap.o
  "_libvlc_media_add_option", referenced from:
      LibVLC::setPath(char const*) in 1686b029_VlcBitmap.o
      LibVLC::useHWacceleration(bool) in 1686b029_VlcBitmap.o
  "_libvlc_media_get_duration", referenced from:
      LibVLC::getDuration() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::videoInitComplete() in 1686b029_VlcBitmap.o
  "_libvlc_media_new_location", referenced from:
      LibVLC::setPath(char const*) in 1686b029_VlcBitmap.o
      LibVLC::openMedia(char const*) in 1686b029_VlcBitmap.o
  "_libvlc_media_parse", referenced from:
      LibVLC::setPath(char const*) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_event_manager", referenced from:
      LibVLC::play(char const*) in 1686b029_VlcBitmap.o
      LibVLC::playInWindow() in 1686b029_VlcBitmap.o
      LibVLC::playInWindow(char const*) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::play(String) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_get_fps", referenced from:
      LibVLC::getFPS() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::getFPS() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_get_length", referenced from:
      LibVLC::getLength() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::videoInitComplete() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_get_position", referenced from:
      LibVLC::getPosition() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_get_time", referenced from:
      LibVLC::getTime() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::getTime() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_has_vout", referenced from:
      LibVLC::hasVout() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_is_playing", referenced from:
      LibVLC::isPlaying() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_is_seekable", referenced from:
      LibVLC::isSeekable() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_new_from_media", referenced from:
      LibVLC::setPath(char const*) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_next_frame", referenced from:
      LibVLC::nextFrame() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_pause", referenced from:
      LibVLC::pause() in 1686b029_VlcBitmap.o
      LibVLC::resume() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::pause() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::resume() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_play", referenced from:
      LibVLC::play() in 1686b029_VlcBitmap.o
      LibVLC::play(char const*) in 1686b029_VlcBitmap.o
      LibVLC::playInWindow() in 1686b029_VlcBitmap.o
      LibVLC::playInWindow(char const*) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::play(String) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_release", referenced from:
      LibVLC::~LibVLC() in 1686b029_VlcBitmap.o
  "_libvlc_media_player_set_media", referenced from:
      LibVLC::openMedia(char const*) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_set_position", referenced from:
      LibVLC::setPosition(float) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::seek(double) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_set_time", referenced from:
      LibVLC::setTime(long long) in 1686b029_VlcBitmap.o
  "_libvlc_media_player_stop", referenced from:
      LibVLC::stop() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::stop() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::dispose() in 1686b029_VlcBitmap.o
  "_libvlc_media_release", referenced from:
      LibVLC::setPath(char const*) in 1686b029_VlcBitmap.o
  "_libvlc_new", referenced from:
      LibVLC::LibVLC() in 1686b029_VlcBitmap.o
      LibVLC::LibVLC() in 1686b029_VlcBitmap.o
      LibVLC::create() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::onAddedToStage(hx::ObjectPtr<openfl::events::Event_obj>) in 1686b029_VlcBitmap.o
  "_libvlc_release", referenced from:
      LibVLC::~LibVLC() in 1686b029_VlcBitmap.o
  "_libvlc_set_fullscreen", referenced from:
      LibVLC::fullscreen(bool) in 1686b029_VlcBitmap.o
  "_libvlc_video_get_height", referenced from:
      LibVLC::getHeight() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::videoInitComplete() in 1686b029_VlcBitmap.o
  "_libvlc_video_get_width", referenced from:
      LibVLC::getWidth() in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::videoInitComplete() in 1686b029_VlcBitmap.o
  "_libvlc_video_set_callbacks", referenced from:
      LibVLC::play(char const*) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::play(String) in 1686b029_VlcBitmap.o
  "_libvlc_video_set_format_callbacks", referenced from:
      LibVLC::play(char const*) in 1686b029_VlcBitmap.o
      vlc::bitmap::VlcBitmap_obj::play(String) in 1686b029_VlcBitmap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: Process completed with exit code 1.

**Comment by BushTrain460615** [comment]
Shit I forgot to change one more thing

**Comment by LeonGamerPS4** [comment]
buildLinux failed after 2m of checks
while buildMac failed after 29m

**Comment by BushTrain460615** [comment]
I will fix it in a bit when I get home

**Comment by LeonGamerPS4** [comment]
you have to be kidding me

**Comment by BushTrain460615** [comment]
I give up

**Pull request closed without merging**
